[directory."internal"]
type = "internal"
store = "%{DEFAULT_STORE}%"
disable = false

[directory."internal".options]
catch-all = true
subaddressing = true

[directory."internal".cache]
entries = 500
ttl = {positive = '1h', negative = '10m'}
