[store."redis"]
type = "redis"
url = "redis://127.0.0.1"
username = "my_username"
password = "secretpassword"
timeout = "10s"
retries = 3
max-retry-wait = "1s"
min-retry-wait = "500ms"
disable = false
