[store."rocksdb"]
type = "rocksdb"
path = "%{BASE_PATH}%/var/rocksdb"
disable = false

[store."rocksdb".settings]
min-blob-size = 16834
write-buffer-size = 134217728

[store."rocksdb".purge]
frequency = "0 3 *"
